# Generated by Django 3.0.5 on 2020-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('adhar', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=3)),
                ('religion', models.CharField(max_length=30)),
                ('bd', models.DateField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
