# Generated by Django 3.0.5 on 2020-09-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xam',
            name='image1',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xam',
            name='adhar',
            field=models.CharField(max_length=12),
        ),
    ]
