# Generated by Django 3.0.5 on 2020-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xams', '0002_auto_20200923_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xam',
            name='image1',
        ),
        migrations.AlterField(
            model_name='xam',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xam',
            name='religion',
            field=models.CharField(max_length=3),
        ),
    ]
