# Generated by Django 3.0.5 on 2020-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xams', '0003_auto_20200923_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='xam',
            name='pic',
            field=models.ImageField(default=1, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
