# Generated by Django 3.1.2 on 2020-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xams', '0004_xam_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xam',
            name='religion',
            field=models.CharField(max_length=10),
        ),
    ]
